# Generated by Django 4.1.1 on 2022-09-23 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Publications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publications_uid', models.CharField(default='', max_length=50)),
                ('publication_title', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Samples',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_uid', models.CharField(default='', max_length=50)),
                ('sample_name', models.CharField(default='', max_length=50)),
            ],
        ),
    ]
